// Arabic localization for Material-React-Table
export const MRT_Localization_AR = {
    actions: 'إجراءات',
    and: 'و',
    cancel: 'إلغاء',
    changeFilterMode: 'تغيير وضع التصفية',
    changeSearchMode: 'تغيير وضع البحث',
    clearFilter: 'مسح التصفية',
    clearSearch: 'مسح البحث',
    clearSort: 'مسح الفرز',
    clickToCopy: 'انقر للنسخ',
    collapse: 'طي',
    collapseAll: 'طي الكل',
    columnActions: 'إجراءات العمود',
    copiedToClipboard: 'تم النسخ للحافظة',
    dropToGroupBy: 'أفلت للتجميع حسب {column}',
    edit: 'تعديل',
    expand: 'توسيع',
    expandAll: 'توسيع الكل',
    filterArrIncludes: 'يتضمن',
    filterArrIncludesAll: 'يتضمن الكل',
    filterArrIncludesSome: 'يتضمن',
    filterBetween: 'بين',
    filterBetweenInclusive: 'بين شامل',
    filterByColumn: 'تصفية حسب {column}',
    filterContains: 'يحتوي',
    filterEmpty: 'فارغ',
    filterEndsWith: 'ينتهي بـ',
    filterEquals: 'يساوي',
    filterEqualsString: 'يساوي',
    filterFuzzy: 'ضبابي',
    filterGreaterThan: 'أكبر من',
    filterGreaterThanOrEqualTo: 'أكبر من أو يساوي',
    filterInNumberRange: 'بين',
    filterIncludesString: 'يحتوي',
    filterIncludesStringSensitive: 'يحتوي',
    filterLessThan: 'أقل من',
    filterLessThanOrEqualTo: 'أقل من أو يساوي',
    filterMode: 'وضع التصفية: {filterType}',
    filterNotEmpty: 'غير فارغ',
    filterNotEquals: 'لا يساوي',
    filterStartsWith: 'يبدأ بـ',
    filterWeakEquals: 'يساوي',
    filteringByColumn: 'تصفية حسب {column} - {filterType} {filterValue}',
    goToFirstPage: 'الذهاب للصفحة الأولى',
    goToLastPage: 'الذهاب للصفحة الأخيرة',
    goToNextPage: 'الذهاب للصفحة التالية',
    goToPreviousPage: 'الذهاب للصفحة السابقة',
    grab: 'امسك',
    groupByColumn: 'تجميع حسب {column}',
    groupedBy: 'مجمع حسب ',
    hideAll: 'إخفاء الكل',
    hideColumn: 'إخفاء عمود {column}',
    max: 'الأكبر',
    min: 'الأصغر',
    move: 'نقل',
    noRecordsToDisplay: 'لا توجد سجلات للعرض',
    noResultsFound: 'لم يتم العثور على نتائج',
    of: 'من',
    or: 'أو',
    pin: 'تثبيت',
    pinToLeft: 'تثبيت لليسار',
    pinToRight: 'تثبيت لليمين',
    resetColumnSize: 'إعادة تعيين حجم العمود',
    resetOrder: 'إعادة تعيين الترتيب',
    rowActions: 'إجراءات الصف',
    rowNumber: '#',
    rowNumbers: 'أرقام الصفوف',
    rowsPerPage: 'صفوف لكل صفحة',
    save: 'حفظ',
    search: 'بحث',
    selectedCountOfRowCountRowsSelected: '{selectedCount} من {rowCount} صف محدد',
    select: 'تحديد',
    showAll: 'إظهار الكل',
    showAllColumns: 'إظهار كل الأعمدة',
    showHideColumns: 'إظهار/إخفاء الأعمدة',
    showHideFilters: 'إظهار/إخفاء التصفية',
    showHideSearch: 'إظهار/إخفاء البحث',
    sortByColumnAsc: 'فرز تصاعدي حسب {column}',
    sortByColumnDesc: 'فرز تنازلي حسب {column}',
    sortedByColumnAsc: 'مفروز تصاعدي حسب {column}',
    sortedByColumnDesc: 'مفروز تنازلي حسب {column}',
    thenBy: ', ثم بـ ',
    toggleDensity: 'تبديل الكثافة',
    toggleFullScreen: 'تبديل ملء الشاشة',
    toggleSelectAll: 'تبديل تحديد الكل',
    toggleSelectRow: 'تبديل تحديد الصف',
    toggleVisibility: 'تبديل الظهور',
    ungroupByColumn: 'إلغاء التجميع حسب {column}',
    unpin: 'إلغاء التثبيت',
    unpinAll: 'إلغاء تثبيت الكل',
};

// Default table props for center alignment and styling
export const defaultTableProps = {
    localization: MRT_Localization_AR,
    muiTableHeadCellProps: {
        align: 'center',
        sx: {
            fontWeight: 'bold',
            backgroundColor: '#f8fafc',
        }
    },
    muiTableBodyCellProps: {
        align: 'center',
    },
    muiTablePaperProps: {
        elevation: 0,
        sx: {
            border: '1px solid #e2e8f0',
            borderRadius: '12px',
        }
    },
};
