import express from 'express';
import cors from 'cors';
import productRoutes from './routes/product.routes.js';
import { errorHandler } from './middlewares/error.middleware.js';
import unitRoutes from './routes/unit.routes.js';
import countryRoutes from './routes/country.routes.js';
import governateRoutes from './routes/governate.routes.js';
import cityRoutes from './routes/city.routes.js';
import warehouseRoutes from './routes/warehouse.routes.js';
import accountRoutes from './routes/account.routes.js';
import purchaseOrderRoutes from './routes/purchaseOrder.routes.js';
import partyCategoryRoutes from './routes/partyCategory.routes.js';
import partyRoutes from './routes/party.routes.js';
import purchaseOrderItemRoutes from "./routes/purchaseOrderItem.routes.js";
import purchaseInvoiceRoutes from './routes/purchaseInvoices.routes.js';
import purchaseInvoiceItemRoutes from './routes/purchaseInvoiceItem.routes.js';
import inventoryTransactionRoutes from './routes/inventoryTransaction.routes.js';
import inventoryTransactionBatchesRoutes from './routes/inventoryTransactionBatches.routes.js';
import journalEntryLinesRouter from "./routes/journalEntryLine.routes.js";
import paymentRoutes from "./routes/purchasePayment.routes.js";
import chequeRoutes from "./routes/supplierCheque.routes.js";
import accountingSettingRoutes from './routes/accountingSettings.route.js';
import supplierLedgerRoutes from './routes/supplierLedger.routes.js';
import customerLedgerRoutes from './routes/customerLedger.routes.js';
import expenseRoutes from "./routes/expenses.routes.js";
import billOfMaterialRouter from './routes/billOfMaterial.routes.js';
import warehouseTransfersRoutes from './routes/warehouseTransfers.routes.js';
import warehouseTransferItemsRoutes from './routes/warehouseTransferItems.routes.js';
import productCostRoutes from './routes/productCosts.routes.js';
import processesRoutes from './routes/processes.routes.js';
import externalJobOrdersRoutes from './routes/externalJobOrders.routes.js';
import currentInventoryRoutes from "./routes/currentInventory.routes.js";
import jobTitlesRoutes from "./routes/jobTitles.routes.js";
import departmentsRoutes from "./routes/departments.routes.js";
import employeeRoutes from "./routes/employees.routes.js";
import issueVoucherTypesRoutes from './routes/issueVoucherTypes.routes.js';
import issueVoucherTypeAccountsRoutes from "./routes/issueVoucherTypeAccounts.routes.js";
import issueVouchersRoutes from "./routes/issueVouchers.routes.js";
import purchaseReturnsRoutes from "./routes/purchaseReturns.routes.js";
import purchaseReturnItemsRoutes from "./routes/purchaseReturnItems.routes.js";
import salesReturnsRoutes from "./routes/salesReturns.routes.js";
import salesOrderRoutes from "./routes/salesOrders.routes.js";
import salesOrderItemRoutes from "./routes/salesOrderItems.routes.js";
import salesInvoiceRoutes from "./routes/salesInvoices.routes.js";
import salesInvoiceItemRoutes from "./routes/salesInvoiceItems.routes.js";
import batchesRoutes from "./routes/batches.routes.js";
import batchInventoryRoutes from "./routes/batchInventory.routes.js";
import salesInvoicePaymentRoutes from "./routes/salesInvoicePayments.routes.js";
import entryTypesRoutes from "./routes/entryTypes.routes.js";
import journalEntryRoutes from "./routes/journalEntry.routes.js";
import jobOrderCostsRoutes from './routes/jobOrderCosts.routes.js';
import companyRoutes from './routes/company.routes.js';
import chequesRoutes from './routes/cheque.routes.js';
import servicePaymentsRoutes from './routes/servicePayments.routes.js';
import reportsRoutes from './routes/reports.routes.js';
import doctorsRoutes from './routes/doctors.routes.js';
import productTypesRoutes from './routes/productTypes.routes.js';

const app = express();
app.use(cors());
app.use(express.json());


app.get('/api/health', (req, res) => res.json({ ok: true }));
app.use('/api/products', productRoutes);
app.use('/api/units', unitRoutes);
app.use('/api/countries', countryRoutes);
app.use('/api/governates', governateRoutes);
app.use('/api/cities', cityRoutes);
app.use("/api/warehouses", warehouseRoutes);
app.use("/api/accounts", accountRoutes);
app.use("/api/purchase-orders", purchaseOrderRoutes);
app.use("/api/party-categories", partyCategoryRoutes);
app.use("/api/parties", partyRoutes);
app.use("/api/purchase-order-items", purchaseOrderItemRoutes);
app.use("/api/purchase-invoices", purchaseInvoiceRoutes);
app.use("/api/purchase-invoice-items", purchaseInvoiceItemRoutes);
app.use("/api/inventory-transactions", inventoryTransactionRoutes);
app.use("/api/inventory-transaction-batches", inventoryTransactionBatchesRoutes);
app.use("/api/journal-entry-lines", journalEntryLinesRouter);
app.use("/api/purchase-payments", paymentRoutes);
app.use("/api/supplier-cheques", chequeRoutes);
app.use("/api/accounting-settings", accountingSettingRoutes);
app.use("/api/suppliers", supplierLedgerRoutes);
app.use("/api/customers", customerLedgerRoutes);
app.use("/api/expenses", expenseRoutes);
app.use('/api/bill-of-material', billOfMaterialRouter);
app.use("/api/warehouse-transfers", warehouseTransfersRoutes);
app.use("/api/warehouse-transfer-items", warehouseTransferItemsRoutes);
app.use("/api/product-costs", productCostRoutes);
app.use('/uploads', express.static('uploads'));
app.use('/api/processes', processesRoutes);
app.use('/api/external-job-orders', externalJobOrdersRoutes);
app.use("/api/current-inventory", currentInventoryRoutes);
app.use("/api/job-titles", jobTitlesRoutes);
app.use("/api/departments", departmentsRoutes);
app.use("/api/employees", employeeRoutes);
app.use('/api/issue-voucher-types', issueVoucherTypesRoutes);
app.use('/api/issue-voucher-type-accounts', issueVoucherTypeAccountsRoutes);
app.use('/api/issue-vouchers', issueVouchersRoutes);
app.use("/api/purchase-returns", purchaseReturnsRoutes);
app.use("/api/purchase-return-items", purchaseReturnItemsRoutes);
app.use("/api/sales-returns", salesReturnsRoutes);
app.use("/api/sales-orders", salesOrderRoutes);
app.use("/api/sales-order-items", salesOrderItemRoutes);
app.use("/api/sales-invoices", salesInvoiceRoutes);
app.use("/api/sales-invoice-items", salesInvoiceItemRoutes);
app.use("/api/batches", batchesRoutes);
app.use("/api/batch-inventory", batchInventoryRoutes);
app.use("/api/sales-invoice-payments", salesInvoicePaymentRoutes);
app.use("/api/entry-types", entryTypesRoutes);
app.use("/api/journal-entries", journalEntryRoutes);
app.use('/api/job-order-costs', jobOrderCostsRoutes);
app.use('/api/companies', companyRoutes);
app.use('/api/cheques', chequesRoutes);
app.use('/api/service-payments', servicePaymentsRoutes);
app.use('/api/reports', reportsRoutes);
app.use('/api/doctors', doctorsRoutes);
app.use('/api/product-types', productTypesRoutes);

app.use(errorHandler);
export default app;
